# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file_name',
            field=models.FileField(upload_to='documents/files'),
        ),
    ]
