# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20170915_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='notify',
            field=models.ManyToManyField(blank=True, to='documents.Notify'),
        ),
    ]
