# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20170915_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
