# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20170915_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=200)),
                ('datetime_log', models.DateTimeField()),
                ('documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.Documents')),
                ('notify', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.Notify')),
            ],
        ),
    ]
