# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_notify_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify_log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.User_contact'),
        ),
    ]
