# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_notify_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_contact',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
