# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_asterisk', models.IntegerField()),
                ('time', models.TimeField()),
                ('callid', models.CharField(max_length=32)),
                ('queuename', models.CharField(max_length=32)),
                ('agent', models.CharField(max_length=32)),
                ('event', models.CharField(max_length=32)),
                ('data1', models.CharField(max_length=100)),
                ('data2', models.CharField(max_length=100)),
                ('data3', models.CharField(max_length=100)),
                ('data4', models.CharField(max_length=100)),
                ('data5', models.CharField(max_length=100)),
            ],
        ),
    ]
