# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuelog',
            name='time',
        ),
        migrations.AddField(
            model_name='queuelog',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
