# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20180316_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuelog',
            old_name='datetime',
            new_name='date_event',
        ),
    ]
