# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20180316_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuelog',
            name='id_asterisk',
            field=models.IntegerField(unique=True),
        ),
    ]
