# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20180316_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpNoAnswered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_phonegts', models.IntegerField(unique=True)),
                ('callerid', models.CharField(max_length=30)),
                ('calldate', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('retry', models.IntegerField()),
                ('last_calldate', models.DateTimeField(null=True)),
                ('done', models.IntegerField()),
                ('dane_calldate', models.DateTimeField(null=True)),
            ],
        ),
    ]
